### ISSUE TITLE
Song stop playing after some time

### ISSUE THREAD

**Issue by issadarkthing** [issadarkthing/gomu#11]
When the song is about to finish it will stop playing, even though there are songs in the queue list.

**Comment by tramhao** [comment]
Met a similar situation. When press n key and not release, the app will stop responding to any further keys.

**Comment by tramhao** [comment]
I think it's related to the select statement in player.go

I changed a line here:
```
		case <-time.After(500 * time.Millisecond):
```

In such situation, the progress bar is running two times faster. The song is playing ok, but when the progress bar reach the end, it stops playing. I tried to change below code:
```
			if p.i > gomu.playingBar.full {
				p.skip()
				// break next
			}
```
but is not working.

**Comment by issadarkthing** [comment]
Do you know how to reproduce the bug?

**Comment by tramhao** [comment]
I cannot reproduce it. That's why I changed the timer and seems that if the select ended in wrong branch, the result is like the bug.

**Comment by tramhao** [comment]
I think probably if the progress is moved from player.go to playingbar.go, the main loop will be simpler.

**Comment by tramhao** [comment]
Probably a fix:
```
		case <-time.After(time.Second):
			// stop progress bar from progressing when paused
			if !p.isRunning {
				continue
			}

			p.i++
			if p.i >= gomu.playingBar.full {
				done <- struct{}{}
				// break next
			}

			gomu.playingBar.progress <- 1

			speaker.Lock()
			p.position = p.getPosition()
			speaker.Unlock()

			/* if p.i > gomu.playingBar.full {
				break next
			} */

```

**Comment by tramhao** [comment]
I think the problem is, in a small chances, the program will end up when p.i > gomu.playingBar.full.

**Comment by tramhao** [comment]
When I add seek function, the timing messed up a lot, so I had to add many position-1, in order to avoid p.i>gomu.playingBar.full, with the above fix, that could be deleted.

**Comment by issadarkthing** [comment]
Below is totally the culprit. It prevents from next song playing since it breaks out of the loop. I don't know why I did that in the first place but you can totally remove it instead of commenting it.
```go
if p.i > gomu.playingBar.full {
  break next
}
```

**Comment by tramhao** [comment]
Yes I've clean it up and please check the PR. Thanks.
