### ISSUE TITLE
Add a scripting language

### ISSUE THREAD

**Issue by issadarkthing** [issadarkthing/gomu#16]
I want to embed a scripting language for this application. The language will be used to set options, configure keybindings #13 , set event listeners or to run shell command. This will greatly add more flexibility to the configuration.

I found a package that is suitable for this https://github.com/mattn/anko. The language is very simple and integrates well with golang types. It also allows us to define arbitrary golang value into the language. For example, it allows function defined in golang into anko.

Lastly, I just think it will be cool to embed a scripting language. Let me know what you guys think.

**Comment by tramhao** [comment]
Looks very cool to me!

**Comment by kristerj** [comment]
Good idea will look at that library this weekend

**Comment by issadarkthing** [comment]
```go
Keybinds.def_g("ctrl_b", func() {
	# execute shell function and capture stdout and stderr
	out, err = shell(`echo "bruhh"`)
	if err != nil {
		debug_popup("an error occurred")
		return
	}
	debug_popup(out)
})
```
