### ISSUE TITLE
Bug after downloading

### ISSUE THREAD

**Issue by tramhao** [issadarkthing/gomu#17]
Recently I found a reproducible bug. The steps to reproduce it:
1.Pause the play
2. Download a song
3. Add the newly downloaded song to playlist.

Now the playbar progress runs twice speed but the music seems normal. After the progress bar finish, the music will stop and cannot play new songs.

**Comment by tramhao** [comment]
It's not actually related to download. Just pause the play and add a new song to queue. The newly added song will be played at wrong speed(progress bar).

**Comment by issadarkthing** [comment]
Not only that, I noticed that the newly added song to the queue will be automatically played.
