### ISSUE TITLE
Possible bug song played slow

### ISSUE THREAD

**Issue by tramhao** [issadarkthing/gomu#19]
Haven't found a way to reproduce it, but sometimes the song is played slower than normal, means that the tone is lower. I checked player.go, and found speaker.init was called once, with the samplerate of current song. If another song is with different samplerate, it'll be a problem right? 
That being said, I've never met a song was played with higher tone.

**Comment by tramhao** [comment]
Found  a way to reporduce this bug.
1. Add 2 songs to the playlist. The first is with samplerate of 44100 and the 2nd is with sr of 48000.(All songs downloaded by gomu seems to be 48000 but I happen to have an mp3 of 44100 which lead to this bug)
2. When program start, it will play the first song, and init the speaker with 44100 sample rate. No problem now.
3. When finish or skip the 1st song, the second song will be played at 44100 sample rate as well, lead to slower speed and lower tone. 

And this bug probably relate to the song stop playing bug also. Because the 2nd song is played at lower sample rate, the progress bar will reach end before the song finish, thus reach the condition(p.i > gomu.playingbar.full), thus stopped. Make sense, right?

**Comment by tramhao** [comment]
you can check the sample rate with mp3info -p "%Q" 1.mp3

**Comment by issadarkthing** [comment]
This is reproducible and your pr #20 seems to fixed it. I had tried to fix this before but failed.
