### ISSUE TITLE
Lyric support and mp3tag

### ISSUE THREAD

**Issue by tramhao** [issadarkthing/gomu#21]
There are some videos on youtube that have subtitles of different languages, and it could be downloaded with youtube-dl as well. I think we could write it as lyric into mp3 and show it in playingBar(if the timestamp is syncronized) or a different panel(if no timestamp). Several options should be added, for example which language is preferred.

**Comment by issadarkthing** [comment]
I think this will be really cool!

**Comment by issadarkthing** [comment]
I think changing the functionality of a panel or adding a panel will be too much work. I suggest using popup will be easier without having to change much in the codebase.

**Comment by tramhao** [comment]
I could download the subtitles with below code:
```
	langSubtitle := "en,zh-Hans"

	args := []string{
		"--skip-download",
		"--output",
		outputDir,
		"--write-sub",
		"--sub-lang",
		langSubtitle,
		"--convert-subs",
		"lrc",
		url,
	}
```

However, I'm stuck in how to write it into mp3 files. I checked several id3v2 packages and they seems only support uslt(unsynchronized lyrics) and not support sylt(synchronized lyrics). More over, I can't even find a player which support editing or displaying sylt under linux.

**Comment by issadarkthing** [comment]
I don't know if this is good idea but we can use the uslt meta tag to store the lyric and then parse the vtt format using [this](https://pkg.go.dev/github.com/martinlindhe/subtitles) library. From the parsed lyric, we can display the correct text on the screen at the correct time.

**Comment by tramhao** [comment]
That's working but will not be compatible with other players. I think https://github.com/bogem/id3v2/blob/master/framer.go could be used to write SYLT according to the specification and that should be compatible.

**Comment by tramhao** [comment]
I gave up modifying the subtitle lib, instead following your ideas. The code is just working for an hour so please help me check for more errors. Thanks.

**Comment by issadarkthing** [comment]
I found this website which lets us download lyric file https://www.rentanadviser.com/en/subtitles/getsubtitle.aspx but it doesn't have any api for us to interact with. I think I can try to scrape the website

**Comment by issadarkthing** [comment]
#24
