### ISSUE TITLE
Accidentally delete whole directory

### ISSUE THREAD

**Issue by tramhao** [issadarkthing/gomu#31]
I deleted my mp3 directory completely, by accident, but several times.
What I want to do is to clear the queue, but I didn't notice that the focus is not in queue. And right after I confirm the operation(it's too fast by keyboard), I know it's wrong.
Fortunately I have complete backup for 30 days, but I think it's a possible problem.
What's the better logic to solve it?

**Comment by tramhao** [comment]
By the way, arch package checksum is wrong.

**Comment by issadarkthing** [comment]
maybe ask user to type out 'DELETE' for bulk delete confirmation

**Comment by issadarkthing** [comment]
> By the way, arch package checksum is wrong.

I will fix it

**Comment by tramhao** [comment]
> maybe ask user to type out 'DELETE' for bulk delete confirmation

Great idea!

**Comment by issadarkthing** [comment]
resolved #30
