### ISSUE TITLE
lang written doesn't not comply to standard

### ISSUE THREAD

**Issue by tramhao** [issadarkthing/gomu#46]
Currently lang for uslt and sylt are both eng, not actually the language of lyrics.
We could write the actual language easily when fetch lyrics, but for lyrics from youtube, I didn't find any specification for the language extension.
What do you think?

**Comment by issadarkthing** [comment]
> Currently lang for uslt and sylt are both eng, not actually the language of lyrics.

What does it mean?

**Comment by tramhao** [comment]
I mean the language like in below code.

```tag.AddUnsynchronisedLyricsFrame(id3v2.UnsynchronisedLyricsFrame{
			Encoding:          id3v2.EncodingUTF8,
			Language:          "eng",
			ContentDescriptor: lyricTobeWritten.LangExt,
			Lyrics:            lyricTobeWritten.AsLRC(),
		})
```

**Comment by issadarkthing** [comment]
It seems like it can be omitted since we don't reference it anywhere in our code base. We can just use the `ContentDescriptor` to identify the lyric language.

**Comment by tramhao** [comment]
ok for now, maybe dig into this in the future.
