### ISSUE TITLE
Can't change default music dir

### ISSUE THREAD

**Issue by avahe-kellenberger** [issadarkthing/gomu#59]
From the README:
`By default, gomu will look for audio files in ~/music directory.`

This doesn't seem to be true; it looks in the `~/Music` directory.

I tried changing it to `~/music` in the config but it had no effect.

**Comment by issadarkthing** [comment]
How do you install it? Also is your config in the correct directory which is `~/.config/gomu`?

**Comment by avahe-kellenberger** [comment]
Haven't tried using it since I wrote the issue; https://github.com/issadarkthing/gomu/issues/61 seems like it may be related. I'll close this for now
